export const metadata = {
  title: 'TopProfile',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
 <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
          </html>
  )
}
